# Week 3, Day 1 — PyTorch Tensors

**Lesson focus:** Tensor creation, shapes, dtypes, devices, indexing, arithmetic, broadcasting, matrix multiplication, and reductions.

**Required evidence:** Complete 12 tensor operations.

Run this notebook from top to bottom using the repository `.venv` kernel.

## Setup

If importing PyTorch fails, activate your `.venv` and install the Project 2 requirements from the repository root:

```powershell
.venv\Scripts\Activate.ps1
pip install -r project_02_transformer_lab/requirements.txt
```

In [1]:
import sys
import subprocess

try:
    import torch
except ModuleNotFoundError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "torch"])
    import torch

torch.manual_seed(42)
operation_results = {}

print('PyTorch version:', torch.__version__)
print('CUDA available:', torch.cuda.is_available())

PyTorch version: 2.11.0+cpu
CUDA available: False


## Operation 1 — Create scalar, vector, and matrix tensors

A scalar has 0 dimensions, a vector has 1 dimension, and a matrix has 2 dimensions.

In [2]:
scalar = torch.tensor(7)
vector = torch.tensor([1, 2, 3])
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])

operation_results[1] = 'Created scalar, vector, and matrix'
print('Scalar:', scalar, '| ndim:', scalar.ndim)
print('Vector:', vector, '| ndim:', vector.ndim)
print('Matrix:\n', matrix, '| ndim:', matrix.ndim)

Scalar: tensor(7) | ndim: 0
Vector: tensor([1, 2, 3]) | ndim: 1
Matrix:
 tensor([[1, 2, 3],
        [4, 5, 6]]) | ndim: 2


## Operation 2 — Create tensors with factory functions

In [3]:
zeros = torch.zeros((2, 3))
ones = torch.ones((2, 3))
filled = torch.full((2, 3), fill_value=5)

operation_results[2] = 'Created zeros, ones, and filled tensors'
print('Zeros:\n', zeros)
print('Ones:\n', ones)
print('Filled with 5:\n', filled)

Zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Filled with 5:
 tensor([[5, 5, 5],
        [5, 5, 5]])


## Operation 3 — Create sequences with `arange` and `linspace`

In [4]:
integer_sequence = torch.arange(start=0, end=10, step=2)
evenly_spaced = torch.linspace(start=0, end=1, steps=5)

operation_results[3] = 'Created numerical sequences'
print('arange:', integer_sequence)
print('linspace:', evenly_spaced)

arange: tensor([0, 2, 4, 6, 8])
linspace: tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


## Operation 4 — Inspect tensor properties

Important properties include shape, number of dimensions, data type, device, and total number of elements.

In [5]:
properties = {
    'shape': tuple(matrix.shape),
    'ndim': matrix.ndim,
    'dtype': str(matrix.dtype),
    'device': str(matrix.device),
    'numel': matrix.numel(),
}

operation_results[4] = 'Inspected tensor properties'
properties

{'shape': (2, 3),
 'ndim': 2,
 'dtype': 'torch.int64',
 'device': 'cpu',
 'numel': 6}

## Operation 5 — Reshape a tensor

Reshaping changes the arrangement but not the number of elements.

In [6]:
original = torch.arange(12)
reshaped = original.reshape(3, 4)
flattened = reshaped.flatten()

operation_results[5] = 'Reshaped and flattened a tensor'
print('Original shape:', original.shape)
print('Reshaped tensor:\n', reshaped)
print('Flattened:', flattened)

Original shape: torch.Size([12])
Reshaped tensor:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Flattened: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


## Operation 6 — Convert tensor data types

Neural-network inputs and parameters commonly use floating-point tensors.

In [7]:
integer_tensor = torch.tensor([1, 2, 3], dtype=torch.int64)
float_tensor = integer_tensor.to(dtype=torch.float32)

operation_results[6] = 'Converted int64 tensor to float32'
print('Before:', integer_tensor, integer_tensor.dtype)
print('After: ', float_tensor, float_tensor.dtype)

Before: tensor([1, 2, 3]) torch.int64
After:  tensor([1., 2., 3.]) torch.float32


## Operation 7 — Select a device and move a tensor

PyTorch uses CUDA when a supported NVIDIA GPU is available; otherwise it safely uses the CPU. Tensors participating in one operation must normally be on the same device.

In [8]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device_tensor = torch.tensor([10.0, 20.0, 30.0]).to(device)

operation_results[7] = f'Moved tensor to {device}'
print('Selected device:', device)
print('Tensor device:', device_tensor.device)

Selected device: cpu
Tensor device: cpu


## Operation 8 — Index and slice a tensor

In [9]:
sample = torch.tensor([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
single_value = sample[1, 2]
first_row = sample[0, :]
second_column = sample[:, 1]

operation_results[8] = 'Indexed values, rows, and columns'
print('Value at row 1, column 2:', single_value.item())
print('First row:', first_row)
print('Second column:', second_column)

Value at row 1, column 2: 60
First row: tensor([10, 20, 30])
Second column: tensor([20, 50, 80])


## Operation 9 — Perform element-wise arithmetic

In [10]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])
addition = a + b
multiplication = a * b
division = b / a

operation_results[9] = 'Performed element-wise arithmetic'
print('Addition:', addition)
print('Multiplication:', multiplication)
print('Division:', division)

Addition: tensor([5., 7., 9.])
Multiplication: tensor([ 4., 10., 18.])
Division: tensor([4.0000, 2.5000, 2.0000])


## Operation 10 — Apply broadcasting

Broadcasting lets PyTorch combine compatible shapes without manually copying the smaller tensor. Here a `(3,)` vector is added to every row of a `(2,3)` matrix.

In [11]:
broadcast_matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
row_vector = torch.tensor([10, 20, 30])
broadcast_result = broadcast_matrix + row_vector

operation_results[10] = 'Broadcast a vector across matrix rows'
print('Matrix shape:', broadcast_matrix.shape)
print('Vector shape:', row_vector.shape)
print('Broadcast result:\n', broadcast_result)

Matrix shape: torch.Size([2, 3])
Vector shape: torch.Size([3])
Broadcast result:
 tensor([[11, 22, 33],
        [14, 25, 36]])


## Operation 11 — Perform matrix multiplication

For `(m × n) @ (n × p)`, the result has shape `(m × p)`.

In [12]:
left = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
right = torch.tensor([[5.0, 6.0], [7.0, 8.0]])
matrix_product = left @ right

operation_results[11] = 'Performed matrix multiplication'
print('Left shape:', left.shape)
print('Right shape:', right.shape)
print('Product:\n', matrix_product)

Left shape: torch.Size([2, 2])
Right shape: torch.Size([2, 2])
Product:
 tensor([[19., 22.],
        [43., 50.]])


## Operation 12 — Calculate reduction statistics

Reduction operations summarize all values or values along a selected dimension.

In [13]:
scores = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
total = scores.sum()
average = scores.mean()
column_means = scores.mean(dim=0)
maximum = scores.max()

operation_results[12] = 'Calculated sum, mean, column means, and maximum'
print('Sum:', total.item())
print('Mean:', average.item())
print('Column means:', column_means)
print('Maximum:', maximum.item())

Sum: 21.0
Mean: 3.5
Column means: tensor([2.5000, 3.5000, 4.5000])
Maximum: 6.0


## Required evidence — verification of all 12 operations

In [14]:
assert scalar.ndim == 0 and vector.ndim == 1 and matrix.ndim == 2
assert zeros.shape == ones.shape == filled.shape == (2, 3)
assert torch.equal(integer_sequence, torch.tensor([0, 2, 4, 6, 8]))
assert properties['numel'] == 6
assert reshaped.shape == (3, 4) and flattened.shape == (12,)
assert float_tensor.dtype == torch.float32
assert device_tensor.device.type == device.type
assert single_value.item() == 60
assert torch.equal(addition, torch.tensor([5.0, 7.0, 9.0]))
assert broadcast_result.shape == (2, 3)
assert torch.equal(matrix_product, torch.tensor([[19.0, 22.0], [43.0, 50.0]]))
assert total.item() == 21.0 and maximum.item() == 6.0
assert sorted(operation_results) == list(range(1, 13))

print('All 12 PyTorch tensor operations passed successfully!')
operation_results

All 12 PyTorch tensor operations passed successfully!


{1: 'Created scalar, vector, and matrix',
 2: 'Created zeros, ones, and filled tensors',
 3: 'Created numerical sequences',
 4: 'Inspected tensor properties',
 5: 'Reshaped and flattened a tensor',
 6: 'Converted int64 tensor to float32',
 7: 'Moved tensor to cpu',
 8: 'Indexed values, rows, and columns',
 9: 'Performed element-wise arithmetic',
 10: 'Broadcast a vector across matrix rows',
 11: 'Performed matrix multiplication',
 12: 'Calculated sum, mean, column means, and maximum'}

## Independent practice

1. Create a tensor of shape `(2, 3, 4)` and report its dimensions and number of elements.
2. Reshape a 24-element tensor into `(4, 6)` and then `(2, 3, 4)`.
3. Broadcast a `(4,)` vector across a `(3, 4)` matrix.
4. Multiply a `(2, 3)` matrix by a `(3, 4)` matrix and predict the output shape before running it.
5. Move a tensor to the available device and then return it to CPU with `.cpu()`.